version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/app:/root"
    tty: true
  backend:
    build: ./backend
    container_name: backend
    ports: 
      - "8000:8000"
    tty: true
