version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/app/components:/usr/src/app/components"
      - "./frontend/app/interfaces:/usr/src/app/interfaces"
      - "./frontend/app/pages:/usr/src/app/pages"
      - "./frontend/app/store:/usr/src/app/store"
      - "./frontend/app/utils:/usr/src/app/utils"
    tty: true
  backend:
    build: ./backend
    container_name: backend
    ports: 
      - "8000:8000"
    tty: true
